<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="_header.jsp" %>

<div class="card qr-scanner-card">
    <div class="page-head">
        <div>
            <p class="eyebrow">SMARTBANK UPI</p>
            <h2>Scan & Pay</h2>
            <p class="muted">Scan a SmartBank QR code, then review the receiver before paying.</p>
        </div>
        <a class="btn light-btn" href="${pageContext.request.contextPath}/dashboard">Back to Dashboard</a>
    </div>

    <div id="reader" class="qr-reader"></div>
    <div id="scanStatus" class="alert" style="display:none"></div>

    <div class="qr-divider"><span>OR</span></div>

    <form id="manualForm" method="get" action="${pageContext.request.contextPath}/upi/pay" class="qr-manual-form">
        <label>Enter SmartBank UPI ID</label>
        <input id="upiId" type="text" name="upiId" placeholder="example123@smartbank" required>
        <button type="submit">Continue to Pay</button>
    </form>

    <p class="muted demo-note">Demo only: camera scanning works for SmartBank QR codes generated by this project. No real UPI money is transferred.</p>
</div>

<script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>
<script>
(function () {
    const status = document.getElementById('scanStatus');
    const context = '${pageContext.request.contextPath}';

    function showStatus(message, type) {
        status.textContent = message;
        status.className = 'alert ' + (type === 'error' ? 'alert-error' : 'alert-success');
        status.style.display = 'block';
    }

    function getUpiId(text) {
        try {
            if (text.indexOf('upi://pay') === 0) {
                const query = text.substring(text.indexOf('?') + 1);
                const params = new URLSearchParams(query);
                return params.get('pa');
            }
        } catch (e) { }
        if (text.indexOf('@smartbank') > -1) return text.trim();
        return null;
    }

    function onScanSuccess(decodedText) {
        const upiId = getUpiId(decodedText);
        if (!upiId) {
            showStatus('This QR is not a SmartBank UPI QR.', 'error');
            return;
        }
        showStatus('QR scanned. Opening payment screen…', 'success');
        window.location.href = context + '/upi/pay?upiId=' + encodeURIComponent(upiId);
    }

    if (window.Html5Qrcode) {
        const scanner = new Html5Qrcode('reader');
        Html5Qrcode.getCameras().then(function (devices) {
            if (!devices || !devices.length) {
                showStatus('No camera found. Use the UPI ID field below.', 'error');
                return;
            }
            scanner.start(
                { facingMode: 'environment' },
                { fps: 10, qrbox: { width: 230, height: 230 } },
                onScanSuccess,
                function () { }
            ).catch(function () {
                showStatus('Camera permission was not available. Use the UPI ID field below.', 'error');
            });
        }).catch(function () {
            showStatus('Camera access is unavailable. Use the UPI ID field below.', 'error');
        });
    } else {
        showStatus('QR scanner library could not load. Use the UPI ID field below.', 'error');
    }
})();
</script>

<%@ include file="_footer.jsp" %>
